### ISSUE TITLE
Is this lib an EasyDeviceInfo rip off !

### ISSUE THREAD

**Issue by nisrulz** [anitaa1990/DeviceInfo-Sample#1]
Not sure about this but it looks like its an [EasyDeviceInfo](https://github.com/nisrulz/easydeviceinfo) rip off. 

if you plan to use open source code , atleast give the author due credit by forking the code.

Thank You

P.S. : I am the author of EasyDeviceInfo library.

https://github.com/nisrulz/easydeviceinfo

**Comment by anitaa1990** [comment]
I have never heard of EasydeviceInfo until you just said it. So please do not accuse of perjury without knowing all the facts! 

I just created a library for my own use. I know how much I struggled with getting all of the device information from an android device and the runtime permissions. And I thought by open sourcing it a lot of people could get help. 

But you have created a nice library by the looks of it. Congrats.
