### ISSUE TITLE
network.getPhoneNumber() issuse

### ISSUE THREAD

**Issue by DeevD** [anitaa1990/DeviceInfo-Sample#3]
It always return empty string bro. How can i get it ?. Some device is can detect bro but latest phones can't detect phone number bro.

**Comment by anitaa1990** [comment]
Phone numbers are not available on SIM for each operators, like in india Sim dont have phone numbers in any memory, So we can't get phone number from these connection. However, some countries, and operators have stored phone numbers on SIM, and we can get those. 

To get the phone number from the device , first you have to set your own phone number on the device, just through : Settings -> About Phone -> Status -> My phone Number

**Comment by DeevD** [comment]
Yes bro thank alot.
