### ISSUE TITLE
What to import in java?

### ISSUE THREAD

**Issue by ni5arga** [anitaa1990/DeviceInfo-Sample#5]
I was trying to use this lib for a project of mine. While compiling I received this error related to the import 
```
   [javac] C:\Users\rubyd\Desktop\extension-template\src\xyz\nisarga\DeviceInfoUtils\DeviceInfoUtils.java:23: error: package com.an does not exist
    [javac] import com.an.deviceinfo;
```
What to import in java?

**Comment by Nisarga-Developer** [comment]
`import com.an.deviceinfo;`
I did this and got compile error

**Comment by ctkqiang** [comment]
Most recommended way is to use gradle .

```
dependencies {
        implementation 'com.an.deviceinfo:deviceinfo:0.1.5'
}
```

**Comment by ni5arga** [comment]
> Most recommended way is to use gradle .
> 
> ```
> dependencies {
>         implementation 'com.an.deviceinfo:deviceinfo:0.1.5'
> }
> ```

Thanks 😊
